### ISSUE TITLE
How to use google-cloud for Vapor 3 despite Vapor 4 updates

### ISSUE THREAD

**Issue by Germantv** [vapor-community/google-cloud-provider#25]
I won’t be able to update my Vapor 3 project to Vapor 4 soon but when i try to build for production, I get some issues since it seems like the library updated its minimum framework requirements to be Vapor 4.

What can I pull in my Package.swift file to avoid any issues and pull google-cloud for Vapor 3?

**Comment by Andrewangeta** [comment]
There's still a branch for [Vapor 3](https://github.com/vapor-community/google-cloud/tree/vapor3)
There's also tagged versions that point to the vapor 3 branch. 
I think the last one was 0.1.3
So specifying that version should get you the vapor 3 compatible version.
Although I highly recommend updating to V4 as soon as you can.
