### ISSUE TITLE
Question: Difference between google-cloud-kit and google-cloud repos

### ISSUE THREAD

**Issue by Frizlab** [vapor-community/google-cloud-provider#28]
I understand google-cloud is a wrapper over google-cloud-kit, however, what does it bring specifically? I don’t see a particular upside to using google-cloud over google-cloud-kit directly in a project.

**Comment by Andrewangeta** [comment]
@Frizlab It’s only meant to have helpful extensions on Vapor’s `Application` and `Request` type to make using them as services easier in Vapor 4. There’s no reason why you can’t use GoogleCloudKit directly.

**Comment by Frizlab** [comment]
Ha! It’s kind of a GoogleCloudKit+Vapor link then. Thanks for the info!
